import { CLASSES, SECTIONS } from '../AssignedClass/assignedClassData'

export const LEAVE_TYPES = [
    'Sick Leave',
    'Casual Leave',
    'Emergency Leave',
    'Family Function',
    'Medical Leave',
]

export const LEAVE_STATUSES = ['Pending', 'Approved', 'Rejected']

export const statusBadgeColor = {
    Pending: 'bg-[#FF980033] text-[#FF9800]',
    Approved: 'bg-[#4CAF5033] text-[#4CAF50]',
    Rejected: 'bg-[#FF000033] text-[#FF0000]',
}

export const LEAVE_REQUESTS = [
    {
        id: 'LR-2001',
        requestId: 'LR-2001',
        studentName: 'Arjun Sharma',
        admissionNumber: 'ADM-2024-1042',
        className: '10',
        section: 'A',
        classSection: '10-A',
        leaveType: 'Sick Leave',
        fromDate: '12-06-2026',
        toDate: '13-06-2026',
        totalDays: 2,
        reason: 'High fever and doctor advised rest for 2 days.',
        parentName: 'Rajesh Sharma',
        parentContact: '+91 98765 43210',
        status: 'Pending',
    },
    {
        id: 'LR-2002',
        requestId: 'LR-2002',
        studentName: 'Priya Nair',
        admissionNumber: 'ADM-2024-1087',
        className: '10',
        section: 'A',
        classSection: '10-A',
        leaveType: 'Family Function',
        fromDate: '15-06-2026',
        toDate: '15-06-2026',
        totalDays: 1,
        reason: 'Attending cousin\'s wedding ceremony out of town.',
        parentName: 'Lakshmi Nair',
        parentContact: '+91 98470 12345',
        status: 'Approved',
    },
    {
        id: 'LR-2003',
        requestId: 'LR-2003',
        studentName: 'Rahul Verma',
        admissionNumber: 'ADM-2024-1156',
        className: '10',
        section: 'A',
        classSection: '10-A',
        leaveType: 'Emergency Leave',
        fromDate: '09-06-2026',
        toDate: '11-06-2026',
        totalDays: 3,
        reason: 'Urgent travel to hometown due to family emergency.',
        parentName: 'Anil Verma',
        parentContact: '+91 91234 56789',
        status: 'Pending',
    },
    {
        id: 'LR-2004',
        requestId: 'LR-2004',
        studentName: 'Sneha Reddy',
        admissionNumber: 'ADM-2024-1203',
        className: '10',
        section: 'A',
        classSection: '10-A',
        leaveType: 'Medical Leave',
        fromDate: '05-06-2026',
        toDate: '07-06-2026',
        totalDays: 3,
        reason: 'Dental surgery recovery; medical certificate submitted.',
        parentName: 'Venkatesh Reddy',
        parentContact: '+91 99887 65432',
        status: 'Approved',
    },
    {
        id: 'LR-2005',
        requestId: 'LR-2005',
        studentName: 'Karthik Menon',
        admissionNumber: 'ADM-2024-1318',
        className: '10',
        section: 'A',
        classSection: '10-A',
        leaveType: 'Casual Leave',
        fromDate: '20-06-2026',
        toDate: '22-06-2026',
        totalDays: 3,
        reason: 'Family vacation planned in advance.',
        parentName: 'Suresh Menon',
        parentContact: '+91 97654 32109',
        status: 'Rejected',
    },
    {
        id: 'LR-2006',
        requestId: 'LR-2006',
        studentName: 'Divya Krishnan',
        admissionNumber: 'ADM-2024-1425',
        className: '10',
        section: 'A',
        classSection: '10-A',
        leaveType: 'Sick Leave',
        fromDate: '18-06-2026',
        toDate: '18-06-2026',
        totalDays: 1,
        reason: 'Stomach infection; unable to attend school.',
        parentName: 'Meera Krishnan',
        parentContact: '+91 96543 21098',
        status: 'Pending',
    },
]

export const getLeaveRequestById = (id) =>
    LEAVE_REQUESTS.find((request) => request.id === id) ?? null

export { CLASSES, SECTIONS }
