import noProfile from '../../../assets/images/no-profile.png'

export const GENDERS = ['Male', 'Female']

export const STUDENTS_LIST = [
    {
        id: 'STU-2024-1042',
        profile: noProfile,
        admissionNumber: 'ADM-2024-1042',
        rollNumber: '10-A-01',
        name: 'Arjun Sharma',
        gender: 'Male',
        email: 'arjun.sharma@student.school.com',
        mobileNumber: '+91 98765 43210',
        dateOfBirth: '15-03-2010',
        country: 'India',
        state: 'Kerala',
        city: 'Kochi',
        className: '10',
        section: 'A',
        classSection: '10-A',
    },
    {
        id: 'STU-2024-1087',
        profile: noProfile,
        admissionNumber: 'ADM-2024-1087',
        rollNumber: '10-A-02',
        name: 'Priya Nair',
        gender: 'Female',
        email: 'priya.nair@student.school.com',
        mobileNumber: '+91 98470 12345',
        dateOfBirth: '22-07-2010',
        country: 'India',
        state: 'Kerala',
        city: 'Thrissur',
        className: '10',
        section: 'A',
        classSection: '10-A',
    },
    {
        id: 'STU-2024-1156',
        profile: noProfile,
        admissionNumber: 'ADM-2024-1156',
        rollNumber: '10-A-03',
        name: 'Rahul Verma',
        gender: 'Male',
        email: 'rahul.verma@student.school.com',
        mobileNumber: '+91 91234 56789',
        dateOfBirth: '08-11-2010',
        country: 'India',
        state: 'Tamil Nadu',
        city: 'Chennai',
        className: '10',
        section: 'A',
        classSection: '10-A',
    },
    {
        id: 'STU-2024-1203',
        profile: noProfile,
        admissionNumber: 'ADM-2024-1203',
        rollNumber: '10-A-04',
        name: 'Sneha Reddy',
        gender: 'Female',
        email: 'sneha.reddy@student.school.com',
        mobileNumber: '+91 99887 65432',
        dateOfBirth: '30-01-2010',
        country: 'India',
        state: 'Telangana',
        city: 'Hyderabad',
        className: '10',
        section: 'A',
        classSection: '10-A',
    },
    {
        id: 'STU-2024-1318',
        profile: noProfile,
        admissionNumber: 'ADM-2024-1318',
        rollNumber: '10-A-05',
        name: 'Karthik Menon',
        gender: 'Male',
        email: 'karthik.menon@student.school.com',
        mobileNumber: '+91 97654 32109',
        dateOfBirth: '04-05-2010',
        country: 'India',
        state: 'Kerala',
        city: 'Kozhikode',
        className: '10',
        section: 'A',
        classSection: '10-A',
    },
    {
        id: 'STU-2024-1425',
        profile: noProfile,
        admissionNumber: 'ADM-2024-1425',
        rollNumber: '10-A-06',
        name: 'Divya Krishnan',
        gender: 'Female',
        email: 'divya.krishnan@student.school.com',
        mobileNumber: '+91 96543 21098',
        dateOfBirth: '18-09-2010',
        country: 'India',
        state: 'Kerala',
        city: 'Thiruvananthapuram',
        className: '10',
        section: 'A',
        classSection: '10-A',
    },
]

export const getStudentById = (id) =>
    STUDENTS_LIST.find((student) => student.id === id) ?? null
