export const EMPLOYEES_LIST = [
    {
        id: 'EMP-1001',
        employeeId: 'TEA-1001',
        name: 'Sandy Selva',
        role: 'Teacher',
        gender: 'Male',
        email: 'san@gmail.com',
        mobileNumber: '9944076993',
        dateOfBirth: '20-12-1996',
        qualification: 'B.SC, B.ED',
        experience: '8 Years',
        country: 'India',
        state: 'Tamil Nadu',
        city: 'Pudukkottai',
    },
    {
        id: 'EMP-1002',
        employeeId: 'TEA-1002',
        name: 'John Milton',
        role: 'Teacher',
        gender: 'Male',
        email: 'John@gmail.com',
        mobileNumber: '9944076994',
        dateOfBirth: '09-07-2000',
        qualification: 'B.SC, B.ED',
        experience: '3.5 Years',
        country: 'India',
        state: 'Tamil Nadu',
        city: 'Madurai',
    },
    {
        id: 'EMP-1003',
        employeeId: 'PRN-1001',
        name: 'Dr. Meena Krishnan',
        role: 'Principal',
        gender: 'Female',
        email: 'meena.krishnan@school.edu',
        mobileNumber: '9876543210',
        dateOfBirth: '15-04-1978',
        qualification: 'M.Ed, Ph.D',
        experience: '18 Years',
        country: 'India',
        state: 'Tamil Nadu',
        city: 'Chennai',
    },
    {
        id: 'EMP-1004',
        employeeId: 'FO-1001',
        name: 'Anita Desai',
        role: 'Front Office',
        gender: 'Female',
        email: 'anita.desai@school.edu',
        mobileNumber: '9123456780',
        dateOfBirth: '22-08-1990',
        qualification: 'B.Com',
        experience: '5 Years',
        country: 'India',
        state: 'Tamil Nadu',
        city: 'Coimbatore',
    },
]

export const getEmployeeById = (id) => {
    const listItem = EMPLOYEES_LIST.find((item) => item.id === id)
    if (!listItem) return null

    const nameParts = listItem.name.replace(/^Dr\.\s*/, '').split(' ')
    return {
        ...listItem,
        profileImage: null,
        userId: `USR-${listItem.employeeId.split('-')[1]}`,
        firstName: nameParts[0] || listItem.name,
        middleName: nameParts.length > 2 ? nameParts.slice(1, -1).join(' ') : '',
        lastName: nameParts.length > 1 ? nameParts[nameParts.length - 1] : '—',
        bloodGroup: 'O+',
        height: '162 cm',
        weight: '58 kg',
        medicalHistory: 'No chronic conditions reported.',
        address: {
            address: '18, Model Town, Block C',
            country: listItem.country,
            state: listItem.state,
            city: listItem.city,
            zipCode: '122002',
        },
        contact: {
            mobileNumber: listItem.mobileNumber,
            alternativeNumber: '+91 91234 56780',
            email: listItem.email,
        },
        professionalInfo: {
            qualification: listItem.qualification,
            subject: listItem.role === 'Teacher' ? 'Mathematics' : '—',
            yearsOfExperience: listItem.experience,
            previousSchool: 'Ryan International School, Sector 40',
            joiningDate: '2019-04-01',
        },
        employmentInfo: {
            employeeType: 'Full-time',
            salary: '₹45,000 / month',
            workShift: 'Morning (8:00 AM – 2:00 PM)',
            assignedClass: listItem.role === 'Teacher' ? 'Class 9, Class 10' : '—',
            assignedSubjects: listItem.role === 'Teacher' ? 'Mathematics, Statistics' : '—',
        },
        account: {
            username: listItem.email.split('@')[0],
            password: 'Employee@123',
        },
        documents: {
            idProof: 'Aadhaar Card',
            qualificationCertificate: `${listItem.qualification} Certificate`,
            experienceCertificate: 'Experience Letter',
        },
    }
}
