import { CLASSES, SECTIONS, SUBJECTS } from '../AssignedClass/assignedClassData'

export const STUDY_MATERIALS = [
    {
        id: 'SM-1001',
        materialId: 'SM-1001',
        subject: 'Mathematics',
        className: '10',
        section: 'A',
        topic: 'Real Numbers',
        materialTitle: 'Real Numbers — Chapter Notes',
        fileName: 'Real_Numbers_Notes.pdf',
        fileType: 'pdf',
        description: 'Comprehensive notes covering Euclid\'s division lemma, irrational numbers, and decimal expansions.',
        uploadDate: '05-06-2026',
    },
    {
        id: 'SM-1002',
        materialId: 'SM-1002',
        subject: 'Mathematics',
        className: '10',
        section: 'A',
        topic: 'Polynomials',
        materialTitle: 'Polynomials — Worksheet & Solutions',
        fileName: 'Polynomials_Worksheet.pdf',
        fileType: 'pdf',
        description: 'Practice worksheet with step-by-step solutions for polynomial zeroes and factorisation.',
        uploadDate: '08-06-2026',
    },
    {
        id: 'SM-1003',
        materialId: 'SM-1003',
        subject: 'Mathematics',
        className: '10',
        section: 'A',
        topic: 'Quadratic Equations',
        materialTitle: 'Quadratic Equations — Video Lecture',
        fileName: 'Quadratic_Equations_Lecture.mp4',
        fileType: 'mp4',
        description: 'Recorded lecture explaining factorisation method and quadratic formula with examples.',
        uploadDate: '10-06-2026',
    },
    {
        id: 'SM-1004',
        materialId: 'SM-1004',
        subject: 'Mathematics',
        className: '10',
        section: 'B',
        topic: 'Trigonometry',
        materialTitle: 'Trigonometric Identities — Reference Sheet',
        fileName: 'Trig_Identities_Sheet.pdf',
        fileType: 'pdf',
        description: 'Quick reference sheet for standard trigonometric identities and proofs.',
        uploadDate: '12-06-2026',
    },
    {
        id: 'SM-1005',
        materialId: 'SM-1005',
        subject: 'Mathematics',
        className: '9',
        section: 'A',
        topic: 'Number Systems',
        materialTitle: 'Number Systems — Presentation',
        fileName: 'Number_Systems_Slides.pptx',
        fileType: 'ppt',
        description: 'Classroom presentation slides for rational and irrational numbers.',
        uploadDate: '14-06-2026',
    },
    {
        id: 'SM-1006',
        materialId: 'SM-1006',
        subject: 'Mathematics',
        className: '11',
        section: 'A',
        topic: 'Sets',
        materialTitle: 'Sets — Concept Map',
        fileName: 'Sets_Concept_Map.pdf',
        fileType: 'pdf',
        description: 'Visual concept map summarising set operations and Venn diagram applications.',
        uploadDate: '16-06-2026',
    },
]

export const getStudyMaterialById = (id) =>
    STUDY_MATERIALS.find((item) => item.id === id) ?? null

export { CLASSES, SECTIONS, SUBJECTS }
