export const singleTitleMapping = {
    "/dashboard": "Dashboard",
    "/admin/dashboard": "Dashboard",

    // Front Office
    "/front-office/dashboard": "Front Office Dashboard",
    "/front-office/admission-enquiry": "Admission Enquiry",
    "/front-office/add-admission-enquiry": "Add Admission Enquiry",
    "/front-office/admission-list": "Admission List",
    "/front-office/add-admission": "Add Admission",
    "/admin/front-office/admission-list": "Admissions",
    "/admin/front-office/add-admission": "Add Admission",
    "/admin/front-office/teachers-list": "Teachers List",
    "/admin/front-office/add-teacher": "Add Teacher",
    "/admin/front-office/librarian-list": "Librarian List",
    "/admin/front-office/add-librarian": "Add Librarian",
    "/admin/front-office/driver-list": "Driver List",
    "/admin/front-office/add-driver": "Add Driver",


    // Attendance
    "/admin/attendance/students-list": "Student Attendance List",
    "/admin/attendance/employees-list": "Employee Attendance List",
    "/admin/attendance/leave-request-list": "My Leave Requests",
    "/admin/attendance/leave-request": "My Leave Requests",


    // Class
    "/admin/class/class-details": "Class Details List",
    "/admin/class/add-class-details": "Add Class Details",
    "/admin/class/online-class": "Online Class List",
    "/admin/class/add-online-class": "Add Online Class",
    "/admin/class/extended-class": "Extended Class List",
    "/admin/class/add-extended-class": "Add Extended Class",
    "/admin/class/timetable-list": "Time Table List",
    "/admin/class/add-timetable": "Add Time Table",
    "/admin/class/subjects": "Subjects List",
    "/admin/class/add-subjects": "Add New Subject",


    // Library Details (Admin)
    "/admin/library-details/book-list": "Book List",
    "/admin/library-details/add-book": "Add Book",
    "/admin/library-details/issued-book": "Issued Book List",
    "/admin/library-details/add-issued-book": "Add Issued Book",


    // Student Details
    "/admin/student/student-details": "Student Details List",
    "/admin/student/class-fee-details": "Class Fee Details List",
    "/admin/student/add-class-fee-details": "Add Class Fee Details",
    "/admin/student/parent-details": "Parent Details List",
    "/admin/student/student-transfer": "Student Transfer List",
    "/admin/student/add-student-transfer": "Add Student Transfer",
    "/admin/student/leave-request": "Student Leave Request List",
    "/admin/student/add-leave-request": "Add Student Leave Request",

    // Activities
    "/admin/activities/cultural-list": "Cultural List",
    "/admin/activities/add-cultural": "Add Cultural Information",
    "/admin/activities/sports-list": "Sports List",
    "/admin/activities/add-sports": "Add Sports Information",
    "/admin/activities/competitions-list": "Competitions List",
    "/admin/activities/add-competition": "Add Competition Information",

    // Documents
    "/admin/documents/student-documents": "Student Documents List",
    "/admin/documents/add-student-documents": "Add Student Documents",

    // Transport
    "/admin/transport/vehicle-details": "Vehicle Details List",
    "/admin/transport/add-vehicle-details": "Add Vehicle Details",
    "/admin/transport/route-details": "Route Details List",
    "/admin/transport/add-route-details": "Add Route Details",
    "/admin/transport/route-data-list": "Route Data List",
    "/admin/transport/assigned-route-list": "Assigned Route List",
    "/admin/transport/assign-route": "Assign Route",

    // Exam Details
    "/admin/exam-details/exam-details-list": "Exam Details List",
    "/admin/exam-details/add-exam-details": "Add Exam Details",

    // Expenses
    "/admin/expenses/salaries-list": "Salaries Expenses List",
    "/admin/expenses/add-salaries-exp": "Add Salaries Expenses",
    "/admin/expenses/hostel-list": "Hostel Expenses List",
    "/admin/expenses/add-hostel-exp": "Add Hostel Expenses",
    "/admin/expenses/transport-list": "Transport Expenses List",
    "/admin/expenses/add-transport-exp": "Add Transport Expenses",
    "/admin/expenses/library-list": "Library Expenses List",
    "/admin/expenses/add-library-exp": "Add Library Expenses",
    "/admin/expenses/others-list": "Others Expenses List",
    "/admin/expenses/add-others-exp": "Add Others Expenses",

    // Notifications
    "/admin/notifications": "Notifications",
    "/admin/notification/exam-list": "Notifications",
    "/admin/notification/event-list": "Notifications",

    // Announcement
    "/admin/announcement": "Announcement List",
    "/admin/announcement/add": "Add Announcement",

    // Task Management
    "/admin/task-management/assign-tasks": "Assign Tasks List",
    "/admin/task-management/assign-tasks/add": "Assign Task",
    "/admin/task-management/assigned-tasks": "Assigned Tasks List",

    // Leave Request
    "/admin/leave-request/my-requests": "My Leave Requests",
    "/admin/leave-request/my-requests/add": "Apply Leave",
    "/admin/leave-request/received": "Received Leave Requests",

    "/admin/escalation-management": "Escalation List",
    "/admin/escalation-management/add-escalation": "Add Escalation",
    "/admin/academic-calendar": "Calendar",
    "/admin/communication/inbox": "Communication Inbox",
    "/admin/communication/direct-messages": "Direct Messages",

    // ── Student Role ──────────────────────────────────────────────────────────
    "/student/dashboard": "Dashboard",
    "/student/class/online-class": "Online Class List",
    "/student/class/extra-class": "Extra Class List",
    "/student/class/timetable-list": "Time Table List",
    "/student/class/attendance-list": "Attendance List",
    "/student/class/attendance-report": "Attendance Report",

    // Studies
    "/student/studies/study-material-list": "Study Material List",
    "/student/studies/sample-questions-list": "Sample Questions List",

    // Student Evaluation
    "/student/student-evaluation/exam-details": "Exam Details",

    // Assessment List
    "/student/assessment/assignment-list": "Assignment List",

    "/student/result-details": "Result Details",

    // Activities
    "/student/activities/cultural-list": "Cultural List",
    "/student/activities/sports-list": "Sports List",
    "/student/activities/competitions-list": "Competitions List",

    // Library
    "/student/library/borrowed-books-list": "Borrowed Books List",

    // Transport
    "/student/transport/bus-route-details": "Bus Route Details",
    "/student/transport/track-bus": "Track Bus Location",

    // Hostel
    "/student/hostel/hostel-details": "Hostel Details",

    // Payemnt Details
    "/student/payment/fees-payment": "Fees Payment Details",
    "/student/payment/hostel-payment": "Hostel Payment Details",
    "/student/payment/transport-payment": "Transport Payment Details",

    // Notification
    "/student/notification/exam-notification": "Exam Notification",
    "/student/notification/event-notification": "Event Notification",
    "/student/notification/holiday-notification": "Holiday Notification",
    "/student/notification/payment-notification": "Payment Notification",

    // Star Ratings
    "/student/star-ratings/view-ratings": "View Star Rating",
    "/student/escalation-management": "Escalation List",
    "/student/escalation-management/add-escalation": "Add Escalation",
    "/student/academic-calendar": "Academic Calendar",
    "/student/communication/inbox": "Communication Inbox",
    "/student/communication/direct-messages": "Direct Messages",

    // ── Librarian Role ────────────────────────────────────────────────────────
    "/librarian/dashboard": "Dashboard",

    // Book Management
    "/librarian/book-management/book-list": "Book List",
    "/librarian/book-management/add-book": "Add Book",

    // Issued Books
    "/librarian/issued-books/issued-book-list": "Issued Book List",
    "/librarian/issued-books/add-issued-book": "Add Issued Book",

    // Members
    "/librarian/members/member-list": "Members List",

    // Notification
    "/librarian/notification/reminder-list": "Reminder List",
    "/librarian/escalation-management": "Escalation List",
    "/librarian/escalation-management/add-escalation": "Add Escalation",
    "/librarian/academic-calendar": "Academic Calendar",
    "/librarian/communication/inbox": "Communication Inbox",
    "/librarian/communication/direct-messages": "Direct Messages",

    "/front-office/student-management": "Student Database",
    "/front-office/teacher-management": "Teacher Database",
    "/front-office/view-student": "View Student",
    "/front-office/view-teacher": "View Teacher",
    "/front-office/student-transfer": "Student Transfer List",
    "/front-office/student-transfer/add": "Add Student Transfer",
    "/front-office/gate-pass-list": "Gate Pass List",
    "/front-office/add-gate-pass": "Add Gate Pass",
    "/front-office/escalation-management": "Escalation List",
    "/front-office/escalation-management/add-escalation": "Add Escalation",
    "/front-office/academic-calendar": "Academic Calendar",
    "/front-office/communication/inbox": "Communication Inbox",
    "/front-office/communication/direct-messages": "Direct Messages",

    // ── Gate Keeper Role ──────────────────────────────────────────────────────
    "/gate-keeper/dashboard": "Dashboard",
    "/gate-keeper/hostel-gate-pass": "Hostel Gate Pass List",
    "/gate-keeper/my-duty": "My Duty List",
    "/gate-keeper/incidents": "Incidents List",
    "/gate-keeper/add-incident": "Add Incident Information",
    "/gate-keeper/gate-pass-list": "Gate Pass List",
    "/gate-keeper/add-gate-pass": "Add Gate Pass",
    "/gate-keeper/broadcast-list": "Announcement List",
    "/gate-keeper/escalation-management": "Escalation List",
    "/gate-keeper/escalation-management/add-escalation": "Add Escalation",
    "/gate-keeper/academic-calendar": "Academic Calendar",
    "/gate-keeper/communication/inbox": "Communication Inbox",
    "/gate-keeper/communication/direct-messages": "Direct Messages",

    // ── Gate Keeper Manager Role ──────────────────────────────────────────────
    "/gatekeeper-manager/dashboard": "Dashboard",
    "/gatekeeper-manager/assign-duty-list": "Assign Duty List",
    "/gatekeeper-manager/assign-duty": "Assign New Duty",
    "/gatekeeper-manager/leave-approval-list": "Leave Approval List",
    "/gatekeeper-manager/incidents-list": "Incidents Management List",
    "/gatekeeper-manager/gatekeeper-broadcast-list": "Gatekeeper Announcement List",
    "/gatekeeper-manager/add-gatekeeper-broadcast": "Add Gatekeeper Announcement",
    "/gatekeeper-manager/escalation-management": "Escalation List",
    "/gatekeeper-manager/escalation-management/add-escalation": "Add Escalation",
    "/gatekeeper-manager/academic-calendar": "Academic Calendar",
    "/gatekeeper-manager/communication/inbox": "Communication Inbox",
    "/gatekeeper-manager/communication/direct-messages": "Direct Messages",

    // ── Canteen Manager Role ──────────────────────────────────────────────────
    "/canteen-manager/dashboard": "Dashboard",
    "/canteen-manager/menu-management": "Menu Management",
    "/canteen-manager/menu-management/add-menu-item": "Add Menu Item",
    "/canteen-manager/inventory": "Inventory Management",
    "/canteen-manager/orders": "Orders",
    "/canteen-manager/orders/add-order": "Add Order",
    "/canteen-manager/requests-approvals": "Requests & Approvals",
    "/canteen-manager/requests-approvals/add-request": "Add Request",
    "/canteen-manager/reports": "Reports",
    "/canteen-manager/broadcast": "Announcement",
    "/canteen-manager/broadcast/add-broadcast": "Add Announcement",

    // ── IT Support Team Manager Role ──────────────────────────────────────────
    "/it-support-manager/dashboard": "Dashboard",
    "/it-support-manager/asset-management": "Asset Management",
    "/it-support-manager/asset-management/add-asset": "Add Asset",
    "/it-support-manager/support-tickets": "Support Tickets",
    "/it-support-manager/requests-approvals": "Requests & Approvals",
    "/it-support-manager/requests-approvals/add-request": "Add Request",
    "/it-support-manager/reports": "Reports",
    "/it-support-manager/broadcast": "Announcement",

    // ── Stationery Store Manager Role ─────────────────────────────────────────
    "/stationery-store-manager/dashboard": "Dashboard",
    "/stationery-store-manager/inventory": "Inventory",
    "/stationery-store-manager/inventory/add-item": "Add Inventory",
    "/stationery-store-manager/issue-returns": "Issue & Returns",
    "/stationery-store-manager/issue-returns/add": "Record Issue / Return",
    "/stationery-store-manager/requests-approvals": "Requests & Approvals",
    "/stationery-store-manager/requests-approvals/add-request": "Add Request",
    "/stationery-store-manager/reports": "Reports",
    "/stationery-store-manager/broadcast": "Announcement",

    // ── Housekeeping Manager Role ─────────────────────────────────────────────
    "/housekeeping-manager/dashboard": "Dashboard",
    "/housekeeping-manager/task-management": "Task Management",
    "/housekeeping-manager/task-management/add-task": "Add Task",
    "/housekeeping-manager/inventory": "Inventory",
    "/housekeeping-manager/inventory/add-item": "Add Inventory",
    "/housekeeping-manager/requests-approvals": "Requests & Approvals",
    "/housekeeping-manager/requests-approvals/add-request": "Add Request",
    "/housekeeping-manager/reports": "Reports",
    "/housekeeping-manager/broadcast": "Announcement",

    // ── Teacher Role ──────────────────────────────────────────────────────────
    "/teacher/dashboard": "Dashboard",
    "/teacher/attendance": "Attendance",
    "/teacher/attendance-history": "Attendance History",
    "/teacher/class/assigned-class": "Assigned Class",
    "/teacher/class/class-routine": "Class Routine",
    "/teacher/class/extra-class": "Extended Class",
    "/teacher/class/extra-class/add": "Add Extended Class",
    "/teacher/class/online-class": "Online Class",
    "/teacher/class/online-class/add": "Add Online Class",
    "/teacher/class/leave-request": "Received Leave Requests",
    "/teacher/leave-request/my-requests": "My Leave Requests",
    "/teacher/leave-request/my-requests/add": "Apply Leave",
    "/teacher/leave-request/received": "Received Leave Requests",
    "/teacher/academics/syllabus": "Syllabus",
    "/teacher/academics/study-materials": "Study Materials",
    "/teacher/academics/study-materials/add": "Add Study Material",
    "/teacher/lesson-plan-approval": "Lesson Plan Approval",
    "/teacher/lesson-plan-approval/add": "Add Lesson Plan",
    "/teacher/student-deliverables/home-fun": "Home Fun",
    "/teacher/student-deliverables/home-fun/add": "Add Assignment / Homework",
    "/teacher/student-deliverables/study-materials": "Study Materials",
    "/teacher/student-deliverables/study-materials/add": "Add Study Material",
    "/teacher/student-deliverables/sample-questions": "Sample Questions",
    "/teacher/user-management/students-list": "Students List",
    "/teacher/user-management/parents-list": "Parents List",
    "/teacher/library/books-borrowed": "Books Borrowed",
    "/teacher/examination/create-schedule": "Create Exam Schedule",
    "/teacher/examination/create-schedule/add": "Create Exam Schedule",
    "/teacher/examination/exam-hall-duty": "Exam Hall Duty",
    "/teacher/student-evaluation/exam-mark": "Exam Mark",
    "/teacher/student-evaluation/exam-schedule": "Exam Schedule",
    "/teacher/student-evaluation/star-ratings": "Star Ratings List",
    "/teacher/student-evaluation/star-ratings/add": "Add Star Ratings",
    "/teacher/student-evaluation/star-of-month": "Star Of Month",
    "/teacher/student-evaluation/questions-banks": "Question Banks List",
    "/teacher/student-evaluation/questions-banks/add": "Add Question Bank",
    "/teacher/student-evaluation/student-transfer": "Student Transfer List",
    "/teacher/marks-results/enter-marks": "Enter Marks List",
    "/teacher/marks-results/enter-marks/add": "Add Marks Entry",
    "/teacher/marks-results/result-summary": "Result Summary List",
    "/teacher/activities/cultural": "Cultural List",
    "/teacher/activities/cultural/add": "Add Cultural Information",
    "/teacher/activities/sports": "Sports List",
    "/teacher/activities/sports/add": "Add Sports Information",
    "/teacher/activities/competitions": "Competitions List",
    "/teacher/activities/competitions/add": "Add Competition Information",
    "/teacher/notifications": "Notifications List",
    "/teacher/announcement": "Announcement List",
    "/teacher/escalation-management": "Escalation List",
    "/teacher/escalation-management/add-escalation": "Add Escalation",
    "/teacher/academic-calendar": "Calendar",
    "/teacher/communication/inbox": "Communication Inbox",
    "/teacher/communication/direct-messages": "Direct Messages",

    // ── Transport Manager Role ────────────────────────────────────────────────
    "/transport-manager/dashboard": "Dashboard",
    "/transport-manager/driver-management": "Driver Management",
    "/transport-manager/vehicle-management": "Vehicle Management",
    "/transport-manager/vehicle-management/add-vehicle": "Add Vehicle",
    "/transport-manager/route-management": "Route Management",
    "/transport-manager/route-management/add-route": "Add Route",
    "/transport-manager/route-data": "Route Data",
    "/transport-manager/student-transport": "Student Transport",
    "/transport-manager/student-transport/add": "Add Student Transport",
    "/transport-manager/assign-duty": "Assign Duty",
    "/transport-manager/assign-duty/add": "Assign Duty",
    "/transport-manager/vehicle-maintenance": "Vehicle Maintenance",
    "/transport-manager/vehicle-maintenance/add": "Vehicle Maintenance",
    "/transport-manager/request-approvals": "Request & Approvals",
    "/transport-manager/transport-expenses": "Transport Expenses",
    "/transport-manager/leave-request": "Leave Request",

    // ── Joint Director Role ───────────────────────────────────────────────────
    "/joint-director/dashboard": "Dashboard",
    "/joint-director/task-management": "Task Management",
    "/joint-director/task-management/add-task": "Add Task",
    "/joint-director/employee-management": "Employee Management",
    "/joint-director/employee-management/jd-assistant": "JD Assistant Profile",
    "/joint-director/employee-management/canteen-manager": "Canteen Manager Profile",
    "/joint-director/employee-management/store-manager": "Store Manager Profile",
    "/joint-director/employee-management/it-team-manager": "IT Team Manager Profile",
    "/joint-director/employee-management/transport-manager": "Transport Manager Profile",
    "/joint-director/employee-management/housekeeping-manager": "House Keeping Manager Profile",
    "/joint-director/employee-management/drivers": "Drivers List",
    "/joint-director/request-approvals": "Request Approvals",
    "/joint-director/request-approvals/view-request": "View Request Details",
    "/joint-director/escalations": "Escalations",
    "/joint-director/meetings-calendar": "Meetings & Calendar",
    "/joint-director/assets-inventory": "Assets & Inventory Overview",
    "/joint-director/broadcast": "Announcement",
    "/joint-director/broadcast/add-broadcast": "Add Announcement",

    // ── Joint Director Assistant Role ─────────────────────────────────────────
    "/joint-director-assistant/dashboard": "Dashboard",
    "/joint-director-assistant/task-management": "Task Management",
    "/joint-director-assistant/task-management/add-task": "Add Task",
    "/joint-director-assistant/employee-management": "Employee Management",
    "/joint-director-assistant/employee-management/canteen-manager": "Canteen Manager Profile",
    "/joint-director-assistant/employee-management/store-manager": "Store Manager Profile",
    "/joint-director-assistant/employee-management/it-team-manager": "IT Team Manager Profile",
    "/joint-director-assistant/employee-management/transport-manager": "Transport Manager Profile",
    "/joint-director-assistant/employee-management/housekeeping-manager": "House Keeping Manager Profile",
    "/joint-director-assistant/employee-management/drivers": "Drivers List",
    "/joint-director-assistant/request-approvals": "Request Approvals",
    "/joint-director-assistant/request-approvals/view-request": "View Request Details",
    "/joint-director-assistant/escalations": "Escalations",
    "/joint-director-assistant/meetings-calendar": "Meetings & Calendar",
    "/joint-director-assistant/assets-inventory": "Assets & Inventory Overview",
    "/joint-director-assistant/broadcast": "Announcement",
    "/joint-director-assistant/broadcast/add-broadcast": "Add Announcement",

    // ── Joint Director Audit Role ───────────────────────────────────────────────
    "/joint-director-audit/dashboard": "Dashboard",
    "/joint-director-audit/audit-configuration": "Audit Configuration",
    "/joint-director-audit/audit-configuration/audit-templates": "Audit Templates",
    "/joint-director-audit/audit-configuration/checklist-sections": "Checklist Sections",
    "/joint-director-audit/audit-configuration/question-bank": "Question Bank",
    "/joint-director-audit/audit-configuration/response-types": "Response Types",
    "/joint-director-audit/audit-configuration/scoring-rules": "Scoring Rules",
    "/joint-director-audit/audit-configuration/workflow-rules": "Workflow Rules",
    "/joint-director-audit/audit-configuration/visibility-rules": "Visibility Rules",
    "/joint-director-audit/audit-configuration/template-versioning": "Template Versioning",
    "/joint-director-audit/audit-configuration/publish-templates": "Publish Templates",
    "/joint-director-audit/audit-assignment": "Audit Assignment",
    "/joint-director-audit/audit-assignment/assign-audits": "Assign Audits",
    "/joint-director-audit/audit-assignment/assignment-history": "Assignment History",
    "/joint-director-audit/audit-assignment/workload-overview": "Workload Overview",
    "/joint-director-audit/audit-assignment/reassign-audit": "Reassign Audit",
    "/joint-director-audit/audit-planning": "Audit Planning",
    "/joint-director-audit/audit-planning/add-audit-plan": "Add Audit Plan",
    "/joint-director-audit/audit-monitoring": "Audit Monitoring",
    "/joint-director-audit/findings-compliance": "Findings & Compliance",
    "/joint-director-audit/reports-analytics": "Reports & Analytics",
    "/joint-director-audit/task-management": "Task Management",
    "/joint-director-audit/task-management/add-task": "Add Task",
    "/joint-director-audit/employee-management": "Employee Management",
    "/joint-director-audit/employee-management/hr-manager": "HR Manager Profile",
    "/joint-director-audit/employee-management/hr-executive": "HR Executive Profile",
    "/joint-director-audit/employee-management/process-audit-manager": "Process Audit Manager Profile",
    "/joint-director-audit/employee-management/process-audit-executive": "Process Audit Executive Profile",
    "/joint-director-audit/employee-management/quality-audit-principal": "Quality Audit Principal Profile",
    "/joint-director-audit/employee-management/quality-audit-executive": "Quality Audit Executive Profile",
    "/joint-director-audit/request-approvals": "Request Approvals",
    "/joint-director-audit/request-approvals/view-request": "View Request Details",
    "/joint-director-audit/escalations": "Escalations",
    "/joint-director-audit/meetings-calendar": "Meetings & Calendar",
    "/joint-director-audit/broadcast": "Announcement",
    "/joint-director-audit/broadcast/add-broadcast": "Add Announcement",

    // ── Process Auditor Role ────────────────────────────────────────────────────
    "/process-auditor/dashboard": "Dashboard",
    "/process-auditor/audit-management/my-audits": "My Audits",
    "/process-auditor/audit-management/audit-schedule": "Audit Schedule",
    "/process-auditor/audit-management/execute-audit": "Execute Audit",
    "/process-auditor/audit-management/audit-history": "Audit History",
    "/process-auditor/observations/open": "Open Observations",
    "/process-auditor/observations/closed": "Closed Observations",
    "/process-auditor/observations/create": "Create Observation",
    "/process-auditor/corrective-actions/escalations": "Escalations",
    "/process-auditor/corrective-actions/escalations/create": "Escalate Observation",
    "/process-auditor/corrective-actions/root-cause-analysis": "Root Cause Analysis",
    "/process-auditor/corrective-actions/action-taken-reports": "Action Taken Reports",
    "/process-auditor/reports": "Reports",
    "/process-auditor/reports/audit-reports": "Audit Reports",
    "/process-auditor/reports/observation-reports": "Observation Reports",
    "/process-auditor/reports/compliance-reports": "Compliance Reports",
    "/process-auditor/reports/pending-actions": "Pending Actions",
    "/process-auditor/reports/closed-actions": "Closed Actions",
    "/process-auditor/communication": "Communication",

    // ── Quality Auditor Role ────────────────────────────────────────────────────
    "/quality-auditor/dashboard": "Dashboard",
    "/quality-auditor/audit-management/my-audits": "My Audits",
    "/quality-auditor/audit-management/audit-schedule": "Audit Schedule",
    "/quality-auditor/audit-management/execute-audit": "Execute Audit",
    "/quality-auditor/audit-management/audit-history": "Audit History",
    "/quality-auditor/observations/open": "Open Observations",
    "/quality-auditor/observations/closed": "Closed Observations",
    "/quality-auditor/observations/create": "Create Observation",
    "/quality-auditor/corrective-actions/escalations": "Escalations",
    "/quality-auditor/corrective-actions/escalations/create": "Escalate Observation",
    "/quality-auditor/corrective-actions/root-cause-analysis": "Root Cause Analysis",
    "/quality-auditor/corrective-actions/action-taken-reports": "Action Taken Reports",
    "/quality-auditor/reports": "Reports",
    "/quality-auditor/reports/audit-reports": "Audit Reports",
    "/quality-auditor/reports/observation-reports": "Observation Reports",
    "/quality-auditor/reports/compliance-reports": "Compliance Reports",
    "/quality-auditor/reports/pending-actions": "Pending Actions",
    "/quality-auditor/reports/closed-actions": "Closed Actions",
    "/quality-auditor/communication": "Communication",

    // ── HR Role ─────────────────────────────────────────────────────────────────
    "/hr/dashboard": "Dashboard",
    "/hr/employee-management": "Employee Management",
    "/hr/employee-management/employees": "Employees",
    "/hr/employee-management/employee-profile": "Employee Profile",
    "/hr/employee-management/documents": "Documents",
    "/hr/recruitment": "Recruitment",
    "/hr/recruitment/job-openings": "Job Openings",
    "/hr/recruitment/candidates": "Candidates",
    "/hr/recruitment/interviews": "Interviews",
    "/hr/onboarding": "Onboarding",
    "/hr/attendance": "Attendance",
    "/hr/leave-management": "Leave Management",
    "/hr/training": "Training",
    "/hr/performance": "Performance",
    "/hr/reports": "Reports",

    // ── Account Head Role ───────────────────────────────────────────────────────
    "/account-head/dashboard": "Finance Dashboard",
    "/account-head/fees-management": "Fees Management",
    "/account-head/transport-finance": "Transport Finance",
    "/account-head/collections": "Collections",
    "/account-head/wallet-management": "Wallet Management",
    "/account-head/accounting": "Accounting",
    "/account-head/accounting/day-book": "Day Book",
    "/account-head/accounting/online-book": "Online Book",
    "/account-head/accounting/general-ledger": "General Ledger",
    "/account-head/accounting/cash-book": "Cash Book",
    "/account-head/accounting/bank-book": "Bank Book",
    "/account-head/accounting/chart-of-accounts": "Chart of Accounts",
    "/account-head/accounting/journal-vouchers": "Journal Vouchers",
    "/account-head/accounting/bank-reconciliation": "Bank Reconciliation",
    "/account-head/accounting/financial-statements": "Financial Statements",
    "/account-head/approvals": "Approvals",
    "/account-head/reports-analytics": "Reports & Analytics",
    "/account-head/settings": "Settings",

    // Driver
    "/driver/dashboard": "Dashboard",
    "/driver/vehicle-management/vehicle-details": "Vehicle Details List",
    "/driver/vehicle-management/vehicle-documents": "Vehicle Documents List",
    "/driver/vehicle-management/vehicle-health-status": "Vehicle Health Status List",
    "/driver/vehicle-management/vehicle-health-status/add": "Add Vehicle Health Status",
    "/driver/my-duty": "My Duty List",
    "/driver/my-route/route-details": "Route Details",
    "/driver/my-route/route-stops": "Route Stops List",
    "/driver/attendance-management/student-attendance": "Student Attendance",
    "/driver/attendance-management/attendance-history": "Attendance History",
    "/driver/fuel-request": "Fuel Request List",
    "/driver/fuel-request/add": "Add Fuel Request",
    "/driver/maintenance-request": "Maintenance Request List",
    "/driver/maintenance-request/add": "Add Maintenance Request",
    "/driver/leave-request": "Leave Request List",
    "/driver/leave-request/add": "Add Leave Request",

    // ── Principal Role ──────────────────────────────────────────────────────────
    "/principal/dashboard": "Dashboard",
    "/principal/documents": "Documents",
    "/principal/documents/add-documents": "Add Documents",
    "/principal/task-management": "Task Management",
    "/principal/task-management/add-task": "Add Task Management",
    "/principal/star-ratings-list": "Star Ratings List",
    "/principal/star-ratings/add-ratings": "Add Ratings",
    "/principal/examination-timetable": "Examination Timetable List",
    "/principal/create-examination-timetable": "Create Examination Timetable",
    "/principal/class-timetable": "Class Timetable List",
    "/principal/create-class-timetable": "Create Class Timetable",
    "/principal/students/student-details-list": "Students List",
    "/principal/students/view-student": "View Student Details",
    "/principal/employees-management/teachers": "Teachers List",
    "/principal/employees-management/view-teacher": "View Teacher Details",
    "/principal/employees-management/coordinators": "Coordinators List",
    "/principal/employees-management/view-coordinator": "View Co-ordinator Details",
    "/principal/employees-management/front-office": "Front Office List",
    "/principal/employees-management/view-front-office": "View Front Office Details",
    "/principal/employees-management/librarians": "Librarian List",
    "/principal/employees-management/view-librarian": "View Librarian Details",
    "/principal/employees-management/gatekeeper-manager": "Gate Keeper Manager List",
    "/principal/employees-management/view-gatekeeper-manager": "View Gate Keeper Manager Details",
    "/principal/employees-management/gatekeepers": "Gate Keepers List",
    "/principal/employees-management/view-gatekeeper": "View Gate Keeper Details",
    "/principal/lms/student-lms": "Student Home Fun",
    "/principal/lms/view-student-lms": "View Student Home Fun Details",
    "/principal/lms/teacher-lms": "Teacher Home Fun",
    "/principal/lms/view-teacher-lms": "View Teacher Home Fun Details",
    "/principal/escalation-management": "Escalation List",
    "/principal/escalation-management/add-escalation": "Add Escalation",
    "/principal/academic-calendar": "Academic Calendar",
    "/principal/communication/inbox": "Communication Inbox",
    "/principal/communication/direct-messages": "Direct Messages",

    // ── Director Role ─────────────────────────────────────────────────────────
    "/director/dashboard": "Dashboard",
    "/director/broadcast": "Announcement",
    "/director/broadcast/add-broadcast": "Add Announcement",
    "/director/task-management": "Task Management",
    "/director/task-management/add-task": "Assign Task",
    "/director/star-ratings/star-of-month": "Star of the Month",
    "/director/star-ratings/star-of-year": "Star of the Year",
    "/director/star-ratings/add-ratings": "Add SOM Rating",
    "/director/examination-approvals": "Exam Timetable Approvals",
    "/director/class-timetable-approvals": "Class Timetable Approvals",
    "/director/user-management/student-database": "Student Database",
    "/director/student-allocation": "Student Allocation",
    "/director/user-management/employee-database": "Employee Database",
    "/director/student-transfer": "Student Transfer List",
    "/director/student-transfer/add": "Add Student Transfer",
    "/director/activities/cultural-list": "Cultural List",
    "/director/activities/add-cultural": "Add Cultural Information",
    "/director/activities/sports-list": "Sports List",
    "/director/activities/add-sports": "Add Sports Information",
    "/director/activities/competitions-list": "Competitions List",
    "/director/activities/add-competition": "Add Competition Information",
    "/director/lms/student-lms": "Student Home Fun",
    "/director/lms/view-student-lms": "View Student Home Fun Details",
    "/director/lms/teacher-lms": "Teacher Home Fun",
    "/director/lms/view-teacher-lms": "View Teacher Home Fun Details",
    "/director/request-approvals": "Request Approvals",
    "/director/request-approvals/view-request": "View Request Details",
    "/director/escalation-management": "Escalation List",
    "/director/escalation-management/add-escalation": "Add Escalation",
    "/director/leave-request/my-requests": "My Leave Requests",
    "/director/leave-request/my-requests/add": "Apply Leave",
    "/director/leave-request/received": "Received Leave Requests",
    "/director/lesson-plan-approval": "Lesson Plan Approval",
    "/director/academic-calendar": "Academic Calendar",
    "/director/communication/inbox": "Communication Inbox",
    "/director/communication/direct-messages": "Direct Messages",
}

/** Paths with params never equal `location.pathname`; match with prefixes / patterns here */
const dynamicTitleMatchers = [
    { test: (p) => /^\/admin\/front-office\/view-teacher\/[^/]+$/.test(p), title: 'Teacher Details' },
    { test: (p) => /^\/admin\/front-office\/view-librarian\/[^/]+$/.test(p), title: 'Librarian Details' },
    { test: (p) => /^\/admin\/front-office\/view-driver\/[^/]+$/.test(p), title: 'Driver Details' },
    { test: (p) => /^\/admin\/front-office\/view-admission\/[^/]+$/.test(p), title: 'Admission Details' },
    { test: (p) => /^\/admin\/front-office\/view-admission-enquiry\/[^/]+$/.test(p), title: 'Admission Enquiry Details' },
    { test: (p) => /^\/admin\/student\/view-student-details\/[^/]+$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/admin\/class\/view-online-class\/[^/]+$/.test(p), title: 'Online Class Details' },
    { test: (p) => /^\/admin\/class\/view-extended-class\/[^/]+$/.test(p), title: 'Extended Class Details' },
    { test: (p) => /^\/admin\/class\/view-timetable\/[^/]+$/.test(p), title: 'Time Table Details' },
    { test: (p) => /^\/admin\/class\/view-subject\/[^/]+$/.test(p), title: 'Subject Details' },
    { test: (p) => /^\/admin\/activities\/view-cultural\/[^/]+$/.test(p), title: 'Cultural Activity Details' },
    { test: (p) => /^\/admin\/activities\/view-sports\/[^/]+$/.test(p), title: 'Sports Activity Details' },
    { test: (p) => /^\/admin\/activities\/view-competition\/[^/]+$/.test(p), title: 'Competition Activity Details' },
    { test: (p) => /^\/director\/user-management\/student-database\/view\/[^/]+$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/director\/user-management\/employee-database\/view\/[^/]+$/.test(p), title: 'View Employee Details' },
    { test: (p) => /^\/director\/student-allocation\/allocate\/[^/]+$/.test(p), title: 'Allocate Student Section' },
    { test: (p) => /^\/director\/activities\/view-cultural\/[^/]+$/.test(p), title: 'Cultural Activity Details' },
    { test: (p) => /^\/director\/activities\/view-sports\/[^/]+$/.test(p), title: 'Sports Activity Details' },
    { test: (p) => /^\/director\/activities\/view-competition\/[^/]+$/.test(p), title: 'Competition Activity Details' },
    { test: (p) => /^\/admin\/documents\/view-student-documents\/[^/]+$/.test(p), title: 'Student Document Details' },
    { test: (p) => /^\/admin\/announcement\/view\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/teacher\/announcement\/view\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/admin\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/admin\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/director\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/director\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/teacher\/leave-request\/my-requests\/view\/[^/]+$/.test(p), title: 'View Leave Request Details' },
    { test: (p) => /^\/teacher\/leave-request\/received\/view\/[^/]+$/.test(p), title: 'View Received Leave Request' },
    { test: (p) => /^\/joint-director\/employee-management\/drivers\/view\/[^/]+$/.test(p), title: 'View Driver Details' },
    { test: (p) => /^\/joint-director-audit\/findings-compliance\/view\/[^/]+$/.test(p), title: 'Finding Details' },
    { test: (p) => /^\/joint-director-audit\/audit-monitoring\/view\/[^/]+$/.test(p), title: 'Audit Monitoring Details' },
    { test: (p) => /^\/joint-director-audit\/audit-planning\/view\/[^/]+$/.test(p), title: 'View Audit Plan' },
    { test: (p) => /^\/joint-director-audit\/audit-planning\/edit\/[^/]+$/.test(p), title: 'Edit Audit Plan' },
    { test: (p) => /^\/joint-director-audit\/escalations\/view-escalation\/[^/]+$/.test(p), title: 'View Escalation Details' },
    { test: (p) => /^\/joint-director-audit\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/joint-director-assistant\/escalations\/view-escalation\/[^/]+$/.test(p), title: 'View Escalation Details' },
    { test: (p) => /^\/joint-director-assistant\/assets-inventory\/view\/[^/]+$/.test(p), title: 'View Asset / Inventory Details' },
    { test: (p) => /^\/joint-director\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/director\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/gate-keeper\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/joint-director\/escalations\/view-escalation\/[^/]+$/.test(p), title: 'View Escalation Details' },
    { test: (p) => /^\/joint-director\/assets-inventory\/view\/[^/]+$/.test(p), title: 'View Asset / Inventory Details' },
    {
        test: (p) =>
            /^\/(admin|director|front-office|gate-keeper|gatekeeper-manager|librarian|principal|student|teacher)\/escalation-management\/view\/[^/]+$/.test(
                p,
            ),
        title: 'View Escalation Details',
    },
    {
        test: (p) =>
            /^\/(admin|director|front-office|gate-keeper|gatekeeper-manager|librarian|principal|student|teacher)\/communication\/direct-messages\/[^/]+$/.test(
                p,
            ),
        title: 'Direct Messages',
    },
    { test: (p) => /^\/principal\/star-ratings\/view-ratings\/[^/]+$/.test(p), title: 'View Star Rating Details' },
    { test: (p) => /^\/teacher\/student-deliverables\/home-fun\/view\/[^/]+$/.test(p), title: 'View Assignment / Homework Details' },
    { test: (p) => /^\/teacher\/student-evaluation\/star-ratings\/view\/[^/]+$/.test(p), title: 'View Star Rating Details' },
    { test: (p) => /^\/teacher\/student-evaluation\/questions-banks\/view\/[^/]+$/.test(p), title: 'View Question Bank Details' },
    { test: (p) => /^\/teacher\/student-evaluation\/student-transfer\/view\/[^/]+$/.test(p), title: 'View Student Transfer Details' },
    { test: (p) => /^\/hr\/employee-management\/employee-profile\/[^/]+$/.test(p), title: 'Employee Profile' },
    { test: (p) => /^\/process-auditor\/audit-management\/my-audits\/view\/[^/]+$/.test(p), title: 'View Audit Details' },
    { test: (p) => /^\/process-auditor\/observations\/view\/[^/]+$/.test(p), title: 'View Observation' },
    { test: (p) => /^\/process-auditor\/corrective-actions\/escalations\/view\/[^/]+$/.test(p), title: 'View Escalation' },
    { test: (p) => /^\/process-auditor\/corrective-actions\/root-cause-analysis\/view\/[^/]+$/.test(p), title: 'View Root Cause Analysis' },
    { test: (p) => /^\/process-auditor\/corrective-actions\/action-taken-reports\/view\/[^/]+$/.test(p), title: 'View Action Taken Report' },
    { test: (p) => /^\/process-auditor\/reports\/audit-reports\/view\/[^/]+$/.test(p), title: 'Audit Report View' },
    { test: (p) => /^\/process-auditor\/reports\/observation-reports\/view\/[^/]+$/.test(p), title: 'Observation Report View' },
    { test: (p) => /^\/quality-auditor\/audit-management\/my-audits\/view\/[^/]+$/.test(p), title: 'View Audit Details' },
    { test: (p) => /^\/quality-auditor\/observations\/view\/[^/]+$/.test(p), title: 'View Observation' },
    { test: (p) => /^\/quality-auditor\/corrective-actions\/escalations\/view\/[^/]+$/.test(p), title: 'View Escalation' },
    { test: (p) => /^\/quality-auditor\/corrective-actions\/root-cause-analysis\/view\/[^/]+$/.test(p), title: 'View Root Cause Analysis' },
    { test: (p) => /^\/quality-auditor\/corrective-actions\/action-taken-reports\/view\/[^/]+$/.test(p), title: 'View Action Taken Report' },
    { test: (p) => /^\/quality-auditor\/reports\/audit-reports\/view\/[^/]+$/.test(p), title: 'Audit Report View' },
    { test: (p) => /^\/quality-auditor\/reports\/observation-reports\/view\/[^/]+$/.test(p), title: 'Observation Report View' },
    { test: (p) => /^\/canteen-manager\/menu-management\/view-menu\/[^/]+$/.test(p), title: 'View Menu Item Details' },
    { test: (p) => /^\/canteen-manager\/orders\/view-order\/[^/]+$/.test(p), title: 'View Order Details' },
    { test: (p) => /^\/canteen-manager\/requests-approvals\/view-request\/[^/]+$/.test(p), title: 'View Request Details' },
    { test: (p) => /^\/canteen-manager\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/it-support-manager\/asset-management\/view-asset\/[^/]+$/.test(p), title: 'View Asset Details' },
    { test: (p) => /^\/it-support-manager\/support-tickets\/view-ticket\/[^/]+$/.test(p), title: 'View Support Ticket' },
    { test: (p) => /^\/it-support-manager\/requests-approvals\/view-request\/[^/]+$/.test(p), title: 'View Request Details' },
    { test: (p) => /^\/it-support-manager\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/stationery-store-manager\/inventory\/view-item\/[^/]+$/.test(p), title: 'View Inventory Item' },
    { test: (p) => /^\/stationery-store-manager\/issue-returns\/view\/[^/]+$/.test(p), title: 'View Issue / Return' },
    { test: (p) => /^\/stationery-store-manager\/requests-approvals\/view-request\/[^/]+$/.test(p), title: 'View Request Details' },
    { test: (p) => /^\/stationery-store-manager\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
    { test: (p) => /^\/transport-manager\/driver-management\/view\/[^/]+$/.test(p), title: 'View Driver Details' },
    { test: (p) => /^\/transport-manager\/vehicle-management\/view\/[^/]+$/.test(p), title: 'View Vehicle Details' },
    { test: (p) => /^\/transport-manager\/vehicle-management\/edit\/[^/]+$/.test(p), title: 'Edit Vehicle' },
    { test: (p) => /^\/transport-manager\/route-management\/view\/[^/]+$/.test(p), title: 'View Route Details' },
    { test: (p) => /^\/transport-manager\/route-management\/edit\/[^/]+$/.test(p), title: 'Edit Route' },
    { test: (p) => /^\/transport-manager\/route-data\/track\/[^/]+$/.test(p), title: 'Track Bus Location' },
    { test: (p) => /^\/transport-manager\/student-transport\/view\/[^/]+$/.test(p), title: 'View Student Transport' },
    { test: (p) => /^\/transport-manager\/assign-duty\/view\/[^/]+$/.test(p), title: 'View Assign Duty' },
    { test: (p) => /^\/transport-manager\/vehicle-maintenance\/view\/[^/]+$/.test(p), title: 'View Vehicle Maintenance' },
    { test: (p) => /^\/transport-manager\/transport-expenses\/add\/fuel$/.test(p), title: 'Add Fuel Expense' },
    { test: (p) => /^\/transport-manager\/transport-expenses\/add\/service$/.test(p), title: 'Add Service Expense' },
    { test: (p) => /^\/transport-manager\/transport-expenses\/add\/other$/.test(p), title: 'Add Other Expense' },
    { test: (p) => /^\/transport-manager\/leave-request\/view\/[^/]+$/.test(p), title: 'View Leave Request' },
    { test: (p) => /^\/transport-manager\/transport-expenses\/view\/[^/]+\/[^/]+$/.test(p), title: 'View Transport Expense' },
    { test: (p) => /^\/teacher\/class\/extra-class\/view\/[^/]+$/.test(p), title: 'View Extended Class' },
    { test: (p) => /^\/teacher\/class\/online-class\/view\/[^/]+$/.test(p), title: 'View Online Class' },
    { test: (p) => /^\/teacher\/academics\/study-materials\/view\/[^/]+$/.test(p), title: 'View Study Material' },
    { test: (p) => /^\/teacher\/student-deliverables\/study-materials\/view\/[^/]+$/.test(p), title: 'View Study Material' },
    { test: (p) => /^\/teacher\/user-management\/students-list\/view\/[^/]+$/.test(p), title: 'View Student Profile' },
    { test: (p) => /^\/teacher\/user-management\/students-list\/view\/[^/]+\/full$/.test(p), title: 'View Student Details' },
    { test: (p) => /^\/driver\/leave-request\/view\/[^/]+$/.test(p), title: 'View Leave Request' },
    { test: (p) => /^\/driver\/leave-request\/edit\/[^/]+$/.test(p), title: 'Edit Leave Request' },
    { test: (p) => /^\/driver\/maintenance-request\/view\/[^/]+$/.test(p), title: 'View Maintenance Request' },
    { test: (p) => /^\/driver\/maintenance-request\/edit\/[^/]+$/.test(p), title: 'Edit Maintenance Request' },
    { test: (p) => /^\/driver\/fuel-request\/view\/[^/]+$/.test(p), title: 'View Fuel Request' },
    { test: (p) => /^\/driver\/fuel-request\/edit\/[^/]+$/.test(p), title: 'Edit Fuel Request' },
    { test: (p) => /^\/driver\/vehicle-management\/vehicle-health-status\/view\/[^/]+$/.test(p), title: 'View Vehicle Health Status' },
    { test: (p) => /^\/driver\/vehicle-management\/vehicle-health-status\/edit\/[^/]+$/.test(p), title: 'Edit Vehicle Health Status' },
    { test: (p) => /^\/housekeeping-manager\/inventory\/view-item\/[^/]+$/.test(p), title: 'View Inventory Item' },
    { test: (p) => /^\/housekeeping-manager\/requests-approvals\/view-request\/[^/]+$/.test(p), title: 'View Request Details' },
    { test: (p) => /^\/housekeeping-manager\/broadcast\/view-broadcast\/[^/]+$/.test(p), title: 'View Announcement Details' },
]

export function getPageTitle(pathname) {
    const exact = singleTitleMapping[pathname]
    if (exact != null) return exact
    const hit = dynamicTitleMatchers.find((m) => m.test(pathname))
    return hit?.title
}
