export {
    LEAVE_TYPES,
    LEAVE_STATUSES,
    statusBadgeColor,
    calculateTotalDays,
    getAllAdminLeaveRequests,
    getAdminLeaveRequestById,
    createAdminLeaveRequest,
    getAdminLeaveRequestById as getMyLeaveRequestById,
} from '../../../Common/AdminLeaveRequest/adminLeaveRequestData'

export const RECEIVED_LEAVE_REQUESTS = [
    {
        id: 'RCV-LR-001',
        leaveRequestId: 'TCH-LR-014',
        requestedBy: 'Priya Sharma',
        role: 'Teacher',
        department: 'Mathematics',
        leaveType: 'Sick Leave',
        fromDate: '18-03-2026',
        toDate: '19-03-2026',
        totalDays: 2,
        appliedDate: '16-03-2026',
        reason: 'High fever and medical certificate attached.',
        status: 'Pending',
    },
    {
        id: 'RCV-LR-002',
        leaveRequestId: 'FO-LR-007',
        requestedBy: 'Anita Desai',
        role: 'Front Office',
        department: 'Administration',
        leaveType: 'Casual Leave',
        fromDate: '22-03-2026',
        toDate: '22-03-2026',
        totalDays: 1,
        appliedDate: '14-03-2026',
        reason: 'Attending parent-teacher association meeting at child\'s school.',
        status: 'Pending',
    },
    {
        id: 'RCV-LR-003',
        leaveRequestId: 'LIB-LR-003',
        requestedBy: 'Meera Iyer',
        role: 'Librarian',
        department: 'Library',
        leaveType: 'Personal Leave',
        fromDate: '10-03-2026',
        toDate: '12-03-2026',
        totalDays: 3,
        appliedDate: '05-03-2026',
        reason: 'Out-of-town documentation work for property registration.',
        status: 'Approved',
    },
    {
        id: 'RCV-LR-004',
        leaveRequestId: 'GK-LR-002',
        requestedBy: 'Ravi Kumar',
        role: 'Gatekeeper',
        department: 'Security',
        leaveType: 'Emergency Leave',
        fromDate: '25-03-2026',
        toDate: '26-03-2026',
        totalDays: 2,
        appliedDate: '24-03-2026',
        reason: 'Family member hospitalised; requires immediate travel.',
        status: 'Pending',
    },
    {
        id: 'RCV-LR-005',
        leaveRequestId: 'TCH-LR-011',
        requestedBy: 'Arjun Menon',
        role: 'Teacher',
        department: 'Science',
        leaveType: 'Medical Leave',
        fromDate: '01-03-2026',
        toDate: '03-03-2026',
        totalDays: 3,
        appliedDate: '27-02-2026',
        reason: 'Post-operative recovery as per doctor\'s recommendation.',
        status: 'Rejected',
    },
]

export const getReceivedLeaveRequestById = (id) =>
    RECEIVED_LEAVE_REQUESTS.find((request) => request.id === id) ?? null
